### ISSUE TITLE
Move to Windows App SDK

### ISSUE THREAD

**Issue by luandersonn** [luandersonn/MyFTP#45]
### Description
I am working on updating the MyFTP app to use Windows UI 3.0. This issue will track the progress and tasks related to this update.

### Tasks
- [x] Add FTPS & SFTP support (#43, #44)
  - [X] FTP
  - [x] FTP**S**
  - [X] **S**FTP
    - [X] Password
    - [ ] Private key
- [ ] Implement asynchronous file/folder operations
  - [x] File download
  - [x] File upload
  - [ ] File renaming
  - [ ] File moving
  - [ ] File deletion
  - [ ] Folder download
  - [ ] Folder upload
  - [ ] Folder renaming
  - [ ] Folder moving
  - [ ] Folder deletion
- [ ] Implement multi-window for hosts
- [ ] Implement Transfer History
- [x] Implement FTP Protocol Handler (#13)
- [x] Add Nickname (#42)
  - [x] Add nickname
  - [x] Update nickname
- [ ] New name?
- [x] Logger
- [ ] Save passwords securely
- [ ] Standalone Installer
- [ ] Website

### Libraries
- FTP and FTPS: [FluentFTP](https://github.com/robinrodricks/FluentFTP)
- SFTP: [SSH.NET](https://github.com/sshnet/SSH.NET)

**Comment by luandersonn** [comment]
### Preview images

#### Login
![Settings - MtFTP WinUI_b1](https://github.com/luandersonn/MyFTP/assets/30560453/1a2e03a7-5400-4cc4-b39c-22b70e12301f)

#### Files (List view)
![Main page - MtFTP WinUI 3_b1](https://github.com/luandersonn/MyFTP/assets/30560453/0a0cf04e-1423-4ac5-927d-fb2c7357c95a)

#### Files (Grid View)

![Main page - MtFTP WinUI 4_b1](https://github.com/luandersonn/MyFTP/assets/30560453/cbf387d2-208b-42f4-bafa-6b3762e6f193)


#### Host settings

![Rebex FTP test - MtFTP WinUI_b1](https://github.com/luandersonn/MyFTP/assets/30560453/7217fdcd-7f7b-412b-9723-158adcd993f6)

**Comment by markox92** [comment]
Huh this looks very promising, just include right click on files options to "Edit file", edit file with notepad or vscode or any other editor....

**Comment by luandersonn** [comment]
> Huh this looks very promising, just include right click on files options to "Edit file", edit file with notepad or vscode or any other editor....

Good one

**Comment by luandersonn** [comment]
Testing a new UI by replacing the TreeView with a TabView ([branch](https://github.com/luandersonn/MyFTP/tree/test-tab-view))

![image](https://github.com/luandersonn/MyFTP/assets/30560453/269415e8-c90c-4fe0-acf2-827e736b884c)

![image](https://github.com/luandersonn/MyFTP/assets/30560453/394c2858-6a38-401d-a9de-714d4802353d)

**Comment by luandersonn** [comment]
UPDATE
![image](https://github.com/luandersonn/MyFTP/assets/30560453/a1e2c883-d0f8-4991-b17f-ecfd1bd4b443)

**Comment by trlef19** [comment]
you can call the app fluenttransfer :))

**Comment by ghost** [comment]
Nice to see work is being done to improve the app and make it work for x86-64 and ARM chips. Hopefully the wait isn't too long. Also good work on the UI for the next version.

I'm not a developer so can't really contribute here but I will keep watching to see what happens here 😃
